// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TripSync.API.Data;

#nullable disable

namespace TripSync.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703212633_Sprint4TripDocuments")]
    partial class Sprint4TripDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");
        }
    }
}
